apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "todo-chatbot.name" . }}
    app.kubernetes.io/component: backend
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
stringData:
  databaseUrl: {{ .Values.backend.env.databaseUrl | quote }}
  secretKey: {{ .Values.backend.env.secretKey | quote }}
  algorithm: {{ .Values.backend.env.algorithm | quote }}
  accessTokenExpireMinutes: {{ .Values.backend.env.accessTokenExpireMinutes | quote }}
